---
# Task to setup the glusterfs repository

- block:
  - name: install CentOS repo
    yum: name={{ item }}  state=present
    with_items:
      - "centos-release-gluster{{ gluster_package_version }}"
  when: ansible_distribution == 'CentOS'
